ALTER TABLE users
ADD COLUMN IF NOT EXISTS login_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS full_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS company_name VARCHAR(150),
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(40),
ADD COLUMN IF NOT EXISTS country VARCHAR(100),
ADD COLUMN IF NOT EXISTS job_title VARCHAR(120),
ADD COLUMN IF NOT EXISTS industry VARCHAR(120),
ADD COLUMN IF NOT EXISTS company_website VARCHAR(255),
ADD COLUMN IF NOT EXISTS profile_completed BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS profile_prompt_required_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS profile_completed_at TIMESTAMP;

UPDATE users
SET profile_completed = (
	full_name IS NOT NULL
	AND company_name IS NOT NULL
	AND phone_number IS NOT NULL
	AND country IS NOT NULL
	AND job_title IS NOT NULL
	AND industry IS NOT NULL
	AND company_website IS NOT NULL
);
